package actions

import (
	"fmt"
	"net/http"

	"github.com/gobuffalo/buffalo"
	"github.com/gobuffalo/pop/v6"
	"github.com/gobuffalo/x/responder"

	"ecom_kart/models"
)

// This file is generated by Buffalo. It offers a basic structure for
// adding, editing and deleting a page. If your model is more
// complex or you need more than the basic implementation you need to
// edit this file.

// Following naming logic is implemented in Buffalo:
// Model: Singular (CartItem)
// DB Table: Plural (cart_items)
// Resource: Plural (CartItems)
// Path: Plural (/cart_items)
// View Template Folder: Plural (/templates/cart_items/)

// CartItemsResource is the resource for the CartItem model
type CartItemsResource struct {
	buffalo.Resource
}

// List gets all CartItems. This function is mapped to the path
// GET /cart_items
func (v CartItemsResource) List(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return fmt.Errorf("no transaction found")
	}

	cartItems := &models.CartItems{}

	// Paginate results. Params "page" and "per_page" control pagination.
	// Default values are "page=1" and "per_page=20".
	q := tx.PaginateFromParams(c.Params())

	// Retrieve all CartItems from the DB
	if err := q.All(cartItems); err != nil {
		return err
	}

	return responder.Wants("html", func(c buffalo.Context) error {
		// Add the paginator to the context so it can be used in the template.
		c.Set("pagination", q.Paginator)

		c.Set("cartItems", cartItems)
		return c.Render(http.StatusOK, r.HTML("cart_items/index.plush.html"))
	}).Wants("json", func(c buffalo.Context) error {
		return c.Render(200, r.JSON(cartItems))
	}).Wants("xml", func(c buffalo.Context) error {
		return c.Render(200, r.XML(cartItems))
	}).Respond(c)
}

// Show gets the data for one CartItem. This function is mapped to
// the path GET /cart_items/{cart_item_id}
func (v CartItemsResource) Show(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return fmt.Errorf("no transaction found")
	}

	// Allocate an empty CartItem
	cartItem := &models.CartItem{}

	// To find the CartItem the parameter cart_item_id is used.
	if err := tx.Find(cartItem, c.Param("cart_item_id")); err != nil {
		return c.Error(http.StatusNotFound, err)
	}

	return responder.Wants("html", func(c buffalo.Context) error {
		c.Set("cartItem", cartItem)

		return c.Render(http.StatusOK, r.HTML("cart_items/show.plush.html"))
	}).Wants("json", func(c buffalo.Context) error {
		return c.Render(200, r.JSON(cartItem))
	}).Wants("xml", func(c buffalo.Context) error {
		return c.Render(200, r.XML(cartItem))
	}).Respond(c)
}

// New renders the form for creating a new CartItem.
// This function is mapped to the path GET /cart_items/new
func (v CartItemsResource) New(c buffalo.Context) error {
	c.Set("cartItem", &models.CartItem{})

	return c.Render(http.StatusOK, r.HTML("cart_items/new.plush.html"))
}

// Create adds a CartItem to the DB. This function is mapped to the
// path POST /cart_items
func (v CartItemsResource) Create(c buffalo.Context) error {
	// Allocate an empty CartItem
	cartItem := &models.CartItem{}

	// Bind cartItem to the html form elements
	if err := c.Bind(cartItem); err != nil {
		return err
	}

	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return fmt.Errorf("no transaction found")
	}

	// Validate the data from the html form
	verrs, err := tx.ValidateAndCreate(cartItem)
	if err != nil {
		return err
	}

	if verrs.HasAny() {
		return responder.Wants("html", func(c buffalo.Context) error {
			// Make the errors available inside the html template
			c.Set("errors", verrs)

			// Render again the new.html template that the user can
			// correct the input.
			c.Set("cartItem", cartItem)

			return c.Render(http.StatusUnprocessableEntity, r.HTML("cart_items/new.plush.html"))
		}).Wants("json", func(c buffalo.Context) error {
			return c.Render(http.StatusUnprocessableEntity, r.JSON(verrs))
		}).Wants("xml", func(c buffalo.Context) error {
			return c.Render(http.StatusUnprocessableEntity, r.XML(verrs))
		}).Respond(c)
	}

	return responder.Wants("html", func(c buffalo.Context) error {
		// If there are no errors set a success message
		c.Flash().Add("success", T.Translate(c, "cartItem.created.success"))

		// and redirect to the show page
		return c.Redirect(http.StatusSeeOther, "/cart_items/%v", cartItem.ID)
	}).Wants("json", func(c buffalo.Context) error {
		return c.Render(http.StatusCreated, r.JSON(cartItem))
	}).Wants("xml", func(c buffalo.Context) error {
		return c.Render(http.StatusCreated, r.XML(cartItem))
	}).Respond(c)
}

// Edit renders a edit form for a CartItem. This function is
// mapped to the path GET /cart_items/{cart_item_id}/edit
func (v CartItemsResource) Edit(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return fmt.Errorf("no transaction found")
	}

	// Allocate an empty CartItem
	cartItem := &models.CartItem{}

	if err := tx.Find(cartItem, c.Param("cart_item_id")); err != nil {
		return c.Error(http.StatusNotFound, err)
	}

	c.Set("cartItem", cartItem)
	return c.Render(http.StatusOK, r.HTML("cart_items/edit.plush.html"))
}

// Update changes a CartItem in the DB. This function is mapped to
// the path PUT /cart_items/{cart_item_id}
func (v CartItemsResource) Update(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return fmt.Errorf("no transaction found")
	}

	// Allocate an empty CartItem
	cartItem := &models.CartItem{}

	if err := tx.Find(cartItem, c.Param("cart_item_id")); err != nil {
		return c.Error(http.StatusNotFound, err)
	}

	// Bind CartItem to the html form elements
	if err := c.Bind(cartItem); err != nil {
		return err
	}

	verrs, err := tx.ValidateAndUpdate(cartItem)
	if err != nil {
		return err
	}

	if verrs.HasAny() {
		return responder.Wants("html", func(c buffalo.Context) error {
			// Make the errors available inside the html template
			c.Set("errors", verrs)

			// Render again the edit.html template that the user can
			// correct the input.
			c.Set("cartItem", cartItem)

			return c.Render(http.StatusUnprocessableEntity, r.HTML("cart_items/edit.plush.html"))
		}).Wants("json", func(c buffalo.Context) error {
			return c.Render(http.StatusUnprocessableEntity, r.JSON(verrs))
		}).Wants("xml", func(c buffalo.Context) error {
			return c.Render(http.StatusUnprocessableEntity, r.XML(verrs))
		}).Respond(c)
	}

	return responder.Wants("html", func(c buffalo.Context) error {
		// If there are no errors set a success message
		c.Flash().Add("success", T.Translate(c, "cartItem.updated.success"))

		// and redirect to the show page
		return c.Redirect(http.StatusSeeOther, "/cart_items/%v", cartItem.ID)
	}).Wants("json", func(c buffalo.Context) error {
		return c.Render(http.StatusOK, r.JSON(cartItem))
	}).Wants("xml", func(c buffalo.Context) error {
		return c.Render(http.StatusOK, r.XML(cartItem))
	}).Respond(c)
}

// Destroy deletes a CartItem from the DB. This function is mapped
// to the path DELETE /cart_items/{cart_item_id}
func (v CartItemsResource) Destroy(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return fmt.Errorf("no transaction found")
	}

	// Allocate an empty CartItem
	cartItem := &models.CartItem{}

	// To find the CartItem the parameter cart_item_id is used.
	if err := tx.Find(cartItem, c.Param("cart_item_id")); err != nil {
		return c.Error(http.StatusNotFound, err)
	}

	if err := tx.Destroy(cartItem); err != nil {
		return err
	}

	return responder.Wants("html", func(c buffalo.Context) error {
		// If there are no errors set a flash message
		c.Flash().Add("success", T.Translate(c, "cartItem.destroyed.success"))

		// Redirect to the index page
		return c.Redirect(http.StatusSeeOther, "/cart_items")
	}).Wants("json", func(c buffalo.Context) error {
		return c.Render(http.StatusOK, r.JSON(cartItem))
	}).Wants("xml", func(c buffalo.Context) error {
		return c.Render(http.StatusOK, r.XML(cartItem))
	}).Respond(c)
}
