package actions

import (
	"fmt"
	"net/http"

	"github.com/gobuffalo/buffalo"
	"github.com/gobuffalo/pop/v6"
	"github.com/gobuffalo/x/responder"

	"ecom_kart/models"
)

// This file is generated by Buffalo. It offers a basic structure for
// adding, editing and deleting a page. If your model is more
// complex or you need more than the basic implementation you need to
// edit this file.

// Following naming logic is implemented in Buffalo:
// Model: Singular (WishlistItem)
// DB Table: Plural (wishlist_items)
// Resource: Plural (WishlistItems)
// Path: Plural (/wishlist_items)
// View Template Folder: Plural (/templates/wishlist_items/)

// WishlistItemsResource is the resource for the WishlistItem model
type WishlistItemsResource struct {
	buffalo.Resource
}

// List gets all WishlistItems. This function is mapped to the path
// GET /wishlist_items
func (v WishlistItemsResource) List(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return fmt.Errorf("no transaction found")
	}

	wishlistItems := &models.WishlistItems{}

	// Paginate results. Params "page" and "per_page" control pagination.
	// Default values are "page=1" and "per_page=20".
	q := tx.PaginateFromParams(c.Params())

	// Retrieve all WishlistItems from the DB
	if err := q.All(wishlistItems); err != nil {
		return err
	}

	return responder.Wants("html", func(c buffalo.Context) error {
		// Add the paginator to the context so it can be used in the template.
		c.Set("pagination", q.Paginator)

		c.Set("wishlistItems", wishlistItems)
		return c.Render(http.StatusOK, r.HTML("wishlist_items/index.plush.html"))
	}).Wants("json", func(c buffalo.Context) error {
		return c.Render(200, r.JSON(wishlistItems))
	}).Wants("xml", func(c buffalo.Context) error {
		return c.Render(200, r.XML(wishlistItems))
	}).Respond(c)
}

// Show gets the data for one WishlistItem. This function is mapped to
// the path GET /wishlist_items/{wishlist_item_id}
func (v WishlistItemsResource) Show(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return fmt.Errorf("no transaction found")
	}

	// Allocate an empty WishlistItem
	wishlistItem := &models.WishlistItem{}

	// To find the WishlistItem the parameter wishlist_item_id is used.
	if err := tx.Find(wishlistItem, c.Param("wishlist_item_id")); err != nil {
		return c.Error(http.StatusNotFound, err)
	}

	return responder.Wants("html", func(c buffalo.Context) error {
		c.Set("wishlistItem", wishlistItem)

		return c.Render(http.StatusOK, r.HTML("wishlist_items/show.plush.html"))
	}).Wants("json", func(c buffalo.Context) error {
		return c.Render(200, r.JSON(wishlistItem))
	}).Wants("xml", func(c buffalo.Context) error {
		return c.Render(200, r.XML(wishlistItem))
	}).Respond(c)
}

// New renders the form for creating a new WishlistItem.
// This function is mapped to the path GET /wishlist_items/new
func (v WishlistItemsResource) New(c buffalo.Context) error {
	c.Set("wishlistItem", &models.WishlistItem{})

	return c.Render(http.StatusOK, r.HTML("wishlist_items/new.plush.html"))
}

// Create adds a WishlistItem to the DB. This function is mapped to the
// path POST /wishlist_items
func (v WishlistItemsResource) Create(c buffalo.Context) error {
	// Allocate an empty WishlistItem
	wishlistItem := &models.WishlistItem{}

	// Bind wishlistItem to the html form elements
	if err := c.Bind(wishlistItem); err != nil {
		return err
	}

	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return fmt.Errorf("no transaction found")
	}

	// Validate the data from the html form
	verrs, err := tx.ValidateAndCreate(wishlistItem)
	if err != nil {
		return err
	}

	if verrs.HasAny() {
		return responder.Wants("html", func(c buffalo.Context) error {
			// Make the errors available inside the html template
			c.Set("errors", verrs)

			// Render again the new.html template that the user can
			// correct the input.
			c.Set("wishlistItem", wishlistItem)

			return c.Render(http.StatusUnprocessableEntity, r.HTML("wishlist_items/new.plush.html"))
		}).Wants("json", func(c buffalo.Context) error {
			return c.Render(http.StatusUnprocessableEntity, r.JSON(verrs))
		}).Wants("xml", func(c buffalo.Context) error {
			return c.Render(http.StatusUnprocessableEntity, r.XML(verrs))
		}).Respond(c)
	}

	return responder.Wants("html", func(c buffalo.Context) error {
		// If there are no errors set a success message
		c.Flash().Add("success", T.Translate(c, "wishlistItem.created.success"))

		// and redirect to the show page
		return c.Redirect(http.StatusSeeOther, "/wishlist_items/%v", wishlistItem.ID)
	}).Wants("json", func(c buffalo.Context) error {
		return c.Render(http.StatusCreated, r.JSON(wishlistItem))
	}).Wants("xml", func(c buffalo.Context) error {
		return c.Render(http.StatusCreated, r.XML(wishlistItem))
	}).Respond(c)
}

// Edit renders a edit form for a WishlistItem. This function is
// mapped to the path GET /wishlist_items/{wishlist_item_id}/edit
func (v WishlistItemsResource) Edit(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return fmt.Errorf("no transaction found")
	}

	// Allocate an empty WishlistItem
	wishlistItem := &models.WishlistItem{}

	if err := tx.Find(wishlistItem, c.Param("wishlist_item_id")); err != nil {
		return c.Error(http.StatusNotFound, err)
	}

	c.Set("wishlistItem", wishlistItem)
	return c.Render(http.StatusOK, r.HTML("wishlist_items/edit.plush.html"))
}

// Update changes a WishlistItem in the DB. This function is mapped to
// the path PUT /wishlist_items/{wishlist_item_id}
func (v WishlistItemsResource) Update(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return fmt.Errorf("no transaction found")
	}

	// Allocate an empty WishlistItem
	wishlistItem := &models.WishlistItem{}

	if err := tx.Find(wishlistItem, c.Param("wishlist_item_id")); err != nil {
		return c.Error(http.StatusNotFound, err)
	}

	// Bind WishlistItem to the html form elements
	if err := c.Bind(wishlistItem); err != nil {
		return err
	}

	verrs, err := tx.ValidateAndUpdate(wishlistItem)
	if err != nil {
		return err
	}

	if verrs.HasAny() {
		return responder.Wants("html", func(c buffalo.Context) error {
			// Make the errors available inside the html template
			c.Set("errors", verrs)

			// Render again the edit.html template that the user can
			// correct the input.
			c.Set("wishlistItem", wishlistItem)

			return c.Render(http.StatusUnprocessableEntity, r.HTML("wishlist_items/edit.plush.html"))
		}).Wants("json", func(c buffalo.Context) error {
			return c.Render(http.StatusUnprocessableEntity, r.JSON(verrs))
		}).Wants("xml", func(c buffalo.Context) error {
			return c.Render(http.StatusUnprocessableEntity, r.XML(verrs))
		}).Respond(c)
	}

	return responder.Wants("html", func(c buffalo.Context) error {
		// If there are no errors set a success message
		c.Flash().Add("success", T.Translate(c, "wishlistItem.updated.success"))

		// and redirect to the show page
		return c.Redirect(http.StatusSeeOther, "/wishlist_items/%v", wishlistItem.ID)
	}).Wants("json", func(c buffalo.Context) error {
		return c.Render(http.StatusOK, r.JSON(wishlistItem))
	}).Wants("xml", func(c buffalo.Context) error {
		return c.Render(http.StatusOK, r.XML(wishlistItem))
	}).Respond(c)
}

// Destroy deletes a WishlistItem from the DB. This function is mapped
// to the path DELETE /wishlist_items/{wishlist_item_id}
func (v WishlistItemsResource) Destroy(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return fmt.Errorf("no transaction found")
	}

	// Allocate an empty WishlistItem
	wishlistItem := &models.WishlistItem{}

	// To find the WishlistItem the parameter wishlist_item_id is used.
	if err := tx.Find(wishlistItem, c.Param("wishlist_item_id")); err != nil {
		return c.Error(http.StatusNotFound, err)
	}

	if err := tx.Destroy(wishlistItem); err != nil {
		return err
	}

	return responder.Wants("html", func(c buffalo.Context) error {
		// If there are no errors set a flash message
		c.Flash().Add("success", T.Translate(c, "wishlistItem.destroyed.success"))

		// Redirect to the index page
		return c.Redirect(http.StatusSeeOther, "/wishlist_items")
	}).Wants("json", func(c buffalo.Context) error {
		return c.Render(http.StatusOK, r.JSON(wishlistItem))
	}).Wants("xml", func(c buffalo.Context) error {
		return c.Render(http.StatusOK, r.XML(wishlistItem))
	}).Respond(c)
}
